// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOP4_xZrRWoPd4emfo66zvP6Y8AnZpBjw',
    appId: '1:269968152898:android:1a936e11338fa3bb7110db',
    messagingSenderId: '269968152898',
    projectId: 'sprints-shopping-app',
    storageBucket: 'sprints-shopping-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpHawKoxkmsRFymxCktNOiVBlYIVcyq64',
    appId: '1:269968152898:ios:76cb17933de0cb447110db',
    messagingSenderId: '269968152898',
    projectId: 'sprints-shopping-app',
    storageBucket: 'sprints-shopping-app.firebasestorage.app',
    iosBundleId: 'com.example.firestoreExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTCDOYomyqdNpZSiGypABFXIKiGGb0Img',
    appId: '1:269968152898:web:f7d2d52e0bfe80847110db',
    messagingSenderId: '269968152898',
    projectId: 'sprints-shopping-app',
    authDomain: 'sprints-shopping-app.firebaseapp.com',
    storageBucket: 'sprints-shopping-app.firebasestorage.app',
    measurementId: 'G-0N5JZ54L60',
  );
}
